### ISSUE TITLE
User adjustable SCAN_INTERVAL_MINUTES?

### ISSUE THREAD

**Issue by Kryzek** [RomRider/ha_nicehash#1]
Hey!
Would it be possible to set `SCAN_INTERVAL_MINUTES` in System options-window? One can always set this manually by editing `const.py` but for the convenience this would be nice to have this in GUI.

**Comment by RomRider** [comment]
I'll look into it, should be possible. At least during initial setup if not possible dynamically afterwards.

**Comment by RomRider** [comment]
This should be good now, default is still 1 minute, but you can increase it up to 30min
