### ISSUE TITLE
Feature Request: Start/stop rig

### ISSUE THREAD

**Issue by n-engelhardt** [RomRider/ha_nicehash#19]
I use my rig as a space heater by mining in the winter. I'd like to be able to automatically start/stop mining based on a temperature sensor. Can you add the ability to start/stop mining with this integration?

**Comment by jcgoette** [comment]
It's a switch.

https://github.com/RomRider/ha_nicehash/blob/aed53dcc3531b96cecad939a8503b6789986806a/custom_components/nicehash/nicehash.py#L114-L123

**Comment by jcgoette** [comment]
It's a switch.

https://github.com/RomRider/ha_nicehash/blob/aed53dcc3531b96cecad939a8503b6789986806a/custom_components/nicehash/nicehash.py#L114-L123

https://github.com/RomRider/ha_nicehash/blob/aed53dcc3531b96cecad939a8503b6789986806a/custom_components/nicehash/switch.py#L137-L152
