### ISSUE TITLE
DAGGERHASHIMOTO - speedAccepted DAGGERHASHIMOTO - speedRejectedTotal not working

### ISSUE THREAD

**Issue by tomcatxx** [RomRider/ha_nicehash#2]
Hi, ty for the nice addon. Everything is working fine. 
Exept the sensors for DAGGERHASHIMOTO - speedAccepted and DAGGERHASHIMOTO - speedRejectedTotal 
![e](https://user-images.githubusercontent.com/69747753/108898087-13983680-7617-11eb-8193-6e905a8eb323.PNG)
Any Ideas?

Edit: nevermind

**Comment by RomRider** [comment]
Is it showing something in NiceHash's web-interface when you select the DaggerHashimoto algorithm in the graph?
![image](https://user-images.githubusercontent.com/21064206/108911399-81e4f500-7627-11eb-8fb8-d2ee383800d2.png)

**Comment by tomcatxx** [comment]
Yes its working now. Reason was that it was mining with Octopus.

**Comment by tomcatxx** [comment]
Ok its strange sometimes its working sometimes not. Atm it hangs on OCTOPUS while mining DAGGERHASHIMOTO for more then 10 minutes. Actualisation timer is set to 1 min.

**Comment by RomRider** [comment]
There might be some delay on the API side. The graph on the NiceHash website would tell you that. If there's a delay there, it would be the same for the data with this component.

**Comment by tomcatxx** [comment]
Yes there is a small delay. Maybe 5 mins. But its not updating for much longer time (>15 mins)

**Comment by RomRider** [comment]
I'll need to figure it out. For me it's only mining ETH for now so it's hard to figure out :)

**Comment by RomRider** [comment]
Found the issue, it should be fixed with the latest release :)
