### ISSUE TITLE
Power switch not working on QuickMiner

### ISSUE THREAD

**Issue by Ndrinta** [RomRider/ha_nicehash#23]
Hi all, I just connected a new rig with QuickMiner NHQM_v0.5.4.3 and I noticed the Power switch doesn't work.
The switch is available in the interface and I can interact with it (not grayed out) but it promptly returns in the previous position if I toggle it.
Is this a known issue or is there a setting I should enable or... it's just my usual luck?

Thanks in advance to anyone willing help me! 😄

**Comment by ivanpavlina** [comment]
It should be fixed in #18 . You can try switching to that branch and test it out.

**Comment by RomRider** [comment]
Since #18 is merged, I'll close this issue
