### ISSUE TITLE
Task exception was never retrieved // TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Zarox666** [RomRider/ha_nicehash#26]
First of all:
Big Thank you for the Apex-Chart Cards.... I cannot imagine building a Dashboard without them anymore.
Unfortunately I do not experience the same level of successs with the ha_nicehash integration.

I am trying to use ha_nicehash for a couple of days now and its giving me great troubles, which I came to believe are not my fault :-)
This is a day-0 issue for me (aka it has never worked) so I cannot say if this might be dependent on the Homeassistant Version (I observe this with Home Assistant 2023.3.3 and Home Assistant 2023.3.4 ) 
I tried to fix my problem myself, but realized that my Programming Skills are by far not good enough to have any chance at it.

Problem:
HA_NiceHash is not updating any of its Entities/Sensors.
When I reload the Integration, or trigger the homeassitant.reload_config_entry service on any of the Entities it succesfully updates the values from nicehash.com.

I tried to workaround the issue, by regularly calling the homeassitant.reload_config_entry from an automation, but that causes a huge memory leak and Homeassistant seizes up in <30 minutes.

If there are any tests, traces or further data you want me to provide, please let me know!

Log Entries:
I found the following Errors in my System Log:
![image](https://user-images.githubusercontent.com/115449639/224951649-89b6bc44-d2aa-450a-81d4-e077a3a6ab46.png)

I think the Task Exception is what gets thrown, while the regular Update should take place, so probably its worth focusing on that:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/nicehash/switch.py:70
Integration: NiceHash (documentation)
First occurred: 08:11:55 (103 occurrences)
Last logged: 09:57:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/config/custom_components/nicehash/switch.py", line 70, in _update_entities
    for dev in rig.get("devices"):
TypeError: 'NoneType' object is not iterable
```

I am not sure if this is a consequence of the Errors that occur during loading the Integration:

```
Logger: homeassistant.components.switch
Source: custom_components/nicehash/switch.py:70
Integration: Switch (documentation, issues)
First occurred: 08:10:55 (3 occurrences)
Last logged: 09:16:47

Error while setting up nicehash platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/nicehash/switch.py", line 87, in async_setup_entry
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 215, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/config/custom_components/nicehash/switch.py", line 70, in _update_entities
    for dev in rig.get("devices"):
TypeError: 'NoneType' object is not iterable
```

```
Logger: homeassistant.components.sensor
Source: custom_components/nicehash/sensor.py:379
Integration: Sensor (documentation, issues)
First occurred: 08:10:55 (3 occurrences)
Last logged: 09:16:47

Error adding entities for domain sensor with platform nicehash
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/nicehash/sensor.py", line 379, in state
    * self.coordinator.data[ACCOUNT_OBJ]["currencies"][0]["fiatRate"]
KeyError: 'fiatRate'
```

```
Logger: homeassistant.components.sensor
Source: custom_components/nicehash/switch.py:70
Integration: Sensor (documentation, issues)
First occurred: 08:10:55 (3 occurrences)
Last logged: 09:16:47

Error while setting up nicehash platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/nicehash/sensor.py", line 120, in async_setup_entry
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 215, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/config/custom_components/nicehash/switch.py", line 70, in _update_entities
    for dev in rig.get("devices"):
TypeError: 'NoneType' object is not iterable
```

**Comment by Zarox666** [comment]
Ok, I made some Progress...

the Problem only seems to happen if I have my ACIS Miners listed on the nicehash.com site.
These devices show with the Tag "UNMANAGED" behind the name and do not show any devices.
![image](https://user-images.githubusercontent.com/115449639/225261870-d96e7106-c133-41fe-8706-0b6787273f3c.png)

Thus rig.get("devices") returns an empty list.
I fixed the problem by putting the for dev in rig.get("devices"): behind an if-clause.

My switch.py @ line 70:
```
           rig_devices = rig.get("devices")
            if rig_devices:
                for dev in rig_devices:
                    device_id = dev.get("id")
                    device_switch = NiceHashDeviceSwitch(
                        hass.data[DOMAIN][config_entry.entry_id][API],
                        coordinator,
                        config_entry,
                        rig_id,
                        device_id,
                    )

```

However the Error with 
```
File "/config/custom_components/nicehash/sensor.py", line 379, in state
    * self.coordinator.data[ACCOUNT_OBJ]["currencies"][0]["fiatRate"]
KeyError: 'fiatRate'
```
still exists and my level of code understanding has not allowed me to fix it yet.
Any Clues or suggestions?

**Comment by RACMan2527** [comment]
Same issue.
Great investigation, Zarox.  Indeed, I believe you have hit on something with the ASICs added to Nicehash.

I have been using the NiceHash integration for several months, and it works great.  I only had GPU miners.
Yesterday I added my fist ASIC to my NiceHash, and noticed all my automations and dashboards in HA halted.

I've added you workaround, and the integration has again resumed updating.  Nice work.

It would be great if the integration could also read the hash rates of the ASICs.  The sensor for 'speedaccepted' and 'rejectedspeed' are created for the ASICs, but they appear as 'unavailable'

I currently have iPollo and Goldshell ASICs, each exhibiting the same symptoms in HA.
In NiceHash Rig Manger, the ASICs show as UNMANAGED, but the hash rates (speeds) are shown in the Rig Manager...so that data is in the NiceHash API, I would think.

take care

**Comment by Zarox666** [comment]
@RACMan2527 
Thanks for the compliment.

Do you also have the Issue with

```
File "/config/custom_components/nicehash/sensor.py", line 379, in state
    * self.coordinator.data[ACCOUNT_OBJ]["currencies"][0]["fiatRate"]
KeyError: 'fiatRate'
```

??
This keeps bugging me and prevents my Sensors from succesfully updating.
Which Currency have you selected during NiceHash setup? Does that even matter?

**Comment by RACMan2527** [comment]
@Zarox666  
I will check later this weekend...have to reinstall.
fiatRate for NiceHash is BCT, I believe; all payments maid in BCT regardless of the coin you mine.

As I was setting up some REST sensors to monitor the ASICs I have on 2miners, I discovered that HA did not like the hyphen (-) in the names of my ASICs.  I remove the hyphen and the REST sensor stopped erroring.  These were the same ASICs I was trying to setup in the niceHash integration...I'm wondering if the integration was also having an issue with the hyphens.
Could be unrelated...

**Comment by Zarox666** [comment]
@RACMan2527 

Thanks for the hint with the Hyphen.... I renamed all miners and reinstalleds the integration, but the error remains unchanged.

I think the problem with the "fiatrate" is somewhere insite the sensor.py as it would indicate that at the point where it is used, there is no "fiatrate" in the (what is it?) Array? Map?
I have not yet understood where exactly this Map or Array gets constructed.

And yes... no matter what you mine, the reward is given in BTC. But I think the Fiat-Rate is the Exchange Rate from BTC to the various FIAT Currencies so the Sensor can display your yield in EUR/USD or whatever you prefer. Afaik these exchange rates are also provided by the NiceHash API, but what I hit there more sounds like a internal logical thing.
And I can happily live with my NiceHash Intergration not providing Echange rates but just bare naked BTC if it only would update properly.

looking forward to your tests.

**Comment by Zarox666** [comment]
I managed to resolve my issue by commenting out every line that contains "fiatrate". Obviously the "Fiatrate" Sensor then stays unavailable, but I can live with that.

Still a permanent Fix from the Developer would be appreciated!.

Thansk!

**Comment by RoaringSon** [comment]
Same TypeError here with rigs that show up as "unmanaged" in nicehash. Fixed it by adding the if statement in switch.py, thanks @Zarox666 .

**Comment by sghebuz** [comment]
> I managed to resolve my issue by commenting out every line that contains "fiatrate". Obviously the "Fiatrate" Sensor then stays unavailable, but I can live with that.
> 
> Still a permanent Fix from the Developer would be appreciated!.
> 
> Thansk!

Please see (and test) https://github.com/RomRider/ha_nicehash/pull/28

**Comment by Zarox666** [comment]
While there is an explanation for the fiatRate Issue the original issue that 
rig.get("devices") can be empty remains unsolved.
After updating I still had to change my switch.py @line 70 again.
@RomRider
